package ar.edu.itba.paw.enums;

public enum Table {
    neighborhoods,
    channels,
    contacts,
    images,
    hours,
    users,
    amenities,
    amenities_hours,
    neighborhoods_channels,
    tags,
    posts,
    posts_tags,
    posts_users_likes,
    posts_users_subscriptions,
    comments,
    events,
    events_users,
    reservations,
    amenities_shifts_availability,
    days,
    users_availability,
    workers_neighborhoods,
    workers_info,
    workers_professions,
    reviews,
    professions,
    shifts,
    times,
    resources,
    products,
    departments,
    products_departments,
    products_users_inquiries,
    products_users_requests,
    products_users_purchases,

}
