services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tomcat-paw
    network_mode: host
    depends_on:
      - db

  webapp-build:
    build:
      context: .
      dockerfile: Dockerfile.build
    container_name: tomcat-paw-build
    network_mode: host
    depends_on:
      - db

  db:
    image: postgres:14
    container_name: postgres-paw
    environment:
      POSTGRES_PASSWORD: superpassword
    ports:
      - "5432:5432"
    volumes:
      - ./docker-init.sql:/docker-entrypoint-initdb.d/init.sql
