services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile.build
    container_name: tomcat-paw-build
    ports:
      - "8079:8080"
    depends_on:
      - db
    networks:
      - pawnet
    logging:
      driver: loki
      options:
        loki-url: "http://localhost:3100/loki/api/v1/push"
        loki-retries: "5"
        loki-batch-size: "400"
        tag: "{{ '{{.ImageName}}' }}|{{ '{{.Name}}' }}"

  db:
    image: postgres:14
    container_name: postgres-paw
    environment:
      POSTGRES_PASSWORD: superpassword
    volumes:
      - ./docker-init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - pawnet
    logging:
      driver: loki
      options:
        loki-url: "http://localhost:3100/loki/api/v1/push"
        loki-retries: "5"
        loki-batch-size: "400"
        tag: "{{ '{{.ImageName}}' }}|{{ '{{.Name}}' }}"

networks:
  pawnet:
    driver: bridge
