services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile.build
    container_name: tomcat-paw-build
    ports:
      - "8079:8080"
    depends_on:
      - db
    networks:
      - pawnet

  db:
    image: postgres:14
    container_name: postgres-paw
    environment:
      POSTGRES_PASSWORD: superpassword
    ports:
      - "5432:5432"
    volumes:
      - ./docker-init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - pawnet

networks:
  pawnet:
    driver: bridge
