// shared/constants/app-title-keys.ts

export const AppTitleKeys = {
  // Admin Section
  ADMIN_AMENITIES_PAGE: 'TITLES.ADMIN_AMENITIES_PAGE',
  ADMIN_AMENITY_CREATE_PAGE: 'TITLES.ADMIN_AMENITY_CREATE_PAGE',
  ADMIN_AMENITY_EDIT_PAGE: 'TITLES.ADMIN_AMENITY_EDIT_PAGE',
  ADMIN_CREATE_ANNOUNCEMENT_PAGE: 'TITLES.ADMIN_CREATE_ANNOUNCEMENT_PAGE',
  ADMIN_CREATE_EVENT_PAGE: 'TITLES.ADMIN_CREATE_EVENT_PAGE',
  ADMIN_INFORMATION_PAGE: 'TITLES.ADMIN_INFORMATION_PAGE',
  ADMIN_NEIGHBORS_REQUESTS_PAGE: 'TITLES.ADMIN_NEIGHBORS_REQUESTS_PAGE',
  ADMIN_NEIGHBORS_LIST_PAGE: 'TITLES.ADMIN_NEIGHBORS_LIST_PAGE',
  ADMIN_SERVICE_PROVIDERS_REQUESTS_PAGE:
    'TITLES.ADMIN_SERVICE_PROVIDERS_REQUESTS_PAGE',
  ADMIN_SERVICE_PROVIDERS_LIST_PAGE: 'TITLES.ADMIN_SERVICE_PROVIDERS_LIST_PAGE',

  // Amenities Section
  AMENITIES_CHOOSE_TIME_PAGE: 'TITLES.AMENITIES_CHOOSE_TIME_PAGE',
  AMENITIES_RESERVATIONS_LIST: 'TITLES.AMENITIES_RESERVATIONS_LIST',
  AMENITIES_RESERVATIONS_PAGE: 'TITLES.AMENITIES_RESERVATIONS_PAGE',

  // Authentication
  LOGIN_PAGE: 'TITLES.LOGIN_PAGE',

  // Calendar Section
  CALENDAR_PAGE: 'TITLES.CALENDAR_PAGE',
  CALENDAR_EVENT_PAGE: 'TITLES.CALENDAR_EVENT_PAGE',

  // Feed Section
  FEED_CREATE_POST_PAGE: 'TITLES.FEED_CREATE_POST_PAGE',
  FEED_PAGE: 'TITLES.FEED_PAGE',
  ANNOUNCEMENTS_PAGE: 'TITLES.ANNOUNCEMENTS_PAGE',
  COMPLAINTS_PAGE: 'TITLES.COMPLAINTS_PAGE',
  FEED_POST_DETAIL_PAGE: 'TITLES.FEED_POST_DETAIL_PAGE',

  // Information Section
  INFORMATION_PAGE: 'TITLES.INFORMATION_PAGE',

  // Marketplace Section
  MARKETPLACE_DASHBOARD_BUYER_PAGE: 'TITLES.MARKETPLACE_DASHBOARD_BUYER_PAGE',
  MARKETPLACE_DASHBOARD_SELLER_PAGE: 'TITLES.MARKETPLACE_DASHBOARD_SELLER_PAGE',
  MARKETPLACE_PAGE: 'TITLES.MARKETPLACE_PAGE',
  MARKETPLACE_PRODUCT_DETAIL_PAGE: 'TITLES.MARKETPLACE_PRODUCT_DETAIL_PAGE',
  MARKETPLACE_PRODUCT_EDIT_PAGE: 'TITLES.MARKETPLACE_PRODUCT_EDIT_PAGE',
  MARKETPLACE_PRODUCT_REQUESTS_PAGE: 'TITLES.MARKETPLACE_PRODUCT_REQUESTS_PAGE',
  MARKETPLACE_PRODUCT_SELL_PAGE: 'TITLES.MARKETPLACE_PRODUCT_SELL_PAGE',

  // Not Found & Rejected
  NOT_FOUND_PAGE: 'TITLES.NOT_FOUND_PAGE',
  REJECTED_PAGE: 'TITLES.REJECTED_PAGE',

  // Service Providers Section
  SERVICE_PROVIDERS_CREATE_POST_PAGE:
    'TITLES.SERVICE_PROVIDERS_CREATE_POST_PAGE',
  SERVICE_PROVIDERS_DETAIL_PAGE: 'TITLES.SERVICE_PROVIDERS_DETAIL_PAGE',
  SERVICE_PROVIDERS_JOIN_NEIGHBORHOODS_PAGE:
    'TITLES.SERVICE_PROVIDERS_JOIN_NEIGHBORHOODS_PAGE',
  SERVICE_PROVIDERS_PAGE: 'TITLES.SERVICE_PROVIDERS_PAGE',

  // Super Admin
  SUPER_ADMIN_PAGE: 'TITLES.SUPER_ADMIN_PAGE',

  // Unverified
  UNVERIFIED_PAGE: 'TITLES.UNVERIFIED_PAGE',

  // User Profile
  USER_PROFILE_PAGE: 'TITLES.USER_PROFILE_PAGE',
};
