export enum Role {
    ADMINISTRATOR = 'ADMINISTRATOR',
    NEIGHBOR = 'NEIGHBOR',
    UNVERIFIED_NEIGHBOR = 'UNVERIFIED_NEIGHBOR',
    WORKER = 'WORKER',
    REJECTED = 'REJECTED',
    SUPER_ADMIN = 'SUPER_ADMIN'
}