// @index('./**/*.ts', f => `export * from '${f.path}'`)
export * from './background-clouds/background-clouds.component'
export * from './background-drawing/background-drawing.component'
export * from './landing-page-navbar/landing-page-navbar.component'
export * from './left-column/left-column.component'
export * from './navbar/navbar.component'
export * from './paginator/paginator.component'
export * from './right-column/right-column.component'
export * from './success-toast/success-toast.component'
export * from './wave-footer/wave-footer.component'
