export enum Roles {
    ADMINISTRATOR = 'ADMINISTRATOR',
    NEIGHBOR = 'NEIGHBOR',
    UNVERIFIED_NEIGHBOR = 'UNVERIFIED_NEIGHBOR',
    WORKER = 'WORKER',
    UNVERIFIED_WORKER = 'UNVERIFIED_WORKER',
    REJECTED = 'REJECTED',
}